# Generated by Django 5.1.4 on 2024-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="threedmodel",
            name="description",
            field=models.TextField(
                default="Здесь могло быть описание модели", verbose_name="описание"
            ),
        ),
    ]
